### ISSUE TITLE
Not possible to launch a streamlit app version after Looker support was added

### ISSUE THREAD

**Issue by sfc-gh-stopchiy** [Snowflake-Labs/semantic-model-generator#157]
Hello,

I tried to launch the streamlit app to generate verified queries from the main branch and it fails with this errror:

2024-09-11 09:23:46.411 Uncaught app exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/stopehiy/github_repos/semantic-model-generator/admin_apps/app.py", line 65, in <module>
    from admin_apps.journeys import builder, iteration, partner
  File "/Users/stopehiy/github_repos/semantic-model-generator/admin_apps/journeys/iteration.py", line 13, in <module>
    from admin_apps.partner.partner_utils import integrate_partner_semantics
  File "/Users/stopehiy/github_repos/semantic-model-generator/admin_apps/partner/partner_utils.py", line 12, in <module>
    from admin_apps.partner.looker import LookerSemanticTable, set_looker_semantic
  File "/Users/stopehiy/github_repos/semantic-model-generator/admin_apps/partner/looker.py", line 489, in <module>
    ) -> None | dict[str, dict[str, str]]:
TypeError: unsupported operand type(s) for |: 'NoneType' and 'types.GenericAlias'

Looks like Looker configuration is required and it fails if it is not set, but I do not use Looker.

Non streamlit version works to generate semantic models but it does not allow to work with verified queries.

After I switched to the release/v0.1.33 version I was able to launch the streamlit app and as I can see that version does not have Looker support (or partners support in general)

Is it possible to add a flag to enable/disable partners?

**Comment by sfc-gh-cnivera** [comment]
Hi @sfc-gh-stopchiy , we just merged a change to make Looker support optional which should prevent this file being imported unless necessary. Could you try pulling `main` and let me know if this issue persists?

If it does, I vaguely recall that type hints are only supported by Python 3.10+. Could you let me know if this issue persists with a different Python version (assuming you are not already on 3.10+)?

**Comment by sfc-gh-stopchiy** [comment]
Hi @sfc-gh-cnivera it works now from the main branch, thank you!
